name: Build APK

on:
  push:
    branches: [ "main" ] # Kodu main branchine attığında çalışır
  workflow_dispatch: # Manuel olarak başlatmanı sağlar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Kodunu GitHub'dan çeker

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: android

      - name: Build apk
        uses: MirkoMajkicProductDock/BuildAPK@v0.0.1
        with:
          flavour: release # Veya senin projenin flavour adı neyse
